name: Daily Solar News Report

on:
  schedule:
    # 08:00 Europe/Stockholm weekdays -> convert to UTC depending DST.
    # Use cron for 07:00 UTC in winter (UTC+1) and 06:00 UTC summer (UTC+2) is complex;
    # simplest: run at 07:00 UTC every weekday (adjust if needed).
    - cron: '0 7 * * 1-5'   # 07:00 UTC (adjust if you want strict local tz)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news reporter
        env:
          RSS_FEEDS: ${{ secrets.RSS_FEEDS }}
          KEYWORDS: ${{ secrets.KEYWORDS }}
          DAYS_BACK: '2'
          MAX_ITEMS: '40'
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          REPORT_TITLE: "WISE Gotland — Daily Solar News Brief"
          OUT_FILE: "report.html"
        run: |
          python news_report.py
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-report
          path: report.html
